### ISSUE TITLE
The cstar issue related to using parameter --host-file

### ISSUE THREAD

**Issue by rjablonovsky** [spotify/cstar#52]
"The Last Pickle" suggested to use cstar (https://github.com/spotify/cstar) as cassandra orchestration tool. The tool was installed on Cassandra LAB servers using the recommended pip3 installation. Testing was done for simple command run (nodetool status), Nodes were identified by parameters: --seed_host, --host, --host-file.
When the parameter --host-file was used with list of nodes in file (separated by newline), a error was observed.
Error details:
```
cat list_nodes.txt
aaaa-aaaa-xca2
baaa-aaaa-xca2

cstar run --command='sudo systemctl restart cassandra' --host-file=list_nodes.txt
Job id is 65316fa8-ffe5-461d-ae7c-9161997ae588
Running /usr/local/lib/python3.6/site-packages/cstar/resources/commands/run.sh
Starting setup
Strategy: topology
DC parallel: True
Cluster parallel: True
Loading cluster topology
Traceback (most recent call last):
  File "/usr/local/bin/cstar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cstar/cstarcli.py", line 132, in main
    namespace.func(namespace)
  File "/usr/local/lib/python3.6/site-packages/cstar/args.py", line 100, in <lambda>
    command_parser.set_defaults(func=lambda args: execute_command(args), command=command)
  File "/usr/local/lib/python3.6/site-packages/cstar/cstarcli.py", line 116, in execute_command
    ssh_lib=args.ssh_lib)
  File "/usr/local/lib/python3.6/site-packages/cstar/job.py", line 209, in setup
    hosts_ip_set = set(socket.gethostbyname(host) for host in hosts)
  File "/usr/local/lib/python3.6/site-packages/cstar/job.py", line 209, in <genexpr>
    hosts_ip_set = set(socket.gethostbyname(host) for host in hosts)
socket.gaierror: [Errno -2] Name or service not known
```

After closer investigation, it appears the error is related to related to retrieving newline as part of host (name, or IP). Ad hock solution was replace the the line 81 in file "/usr/local/lib/python3.6/site-packages/cstar/cstarcli.py" with reading lines without newline:  "hosts = f.read().splitlines()"
Diff details:
```
diff /usr/local/lib/python3.6/site-packages/cstar/cstarcli.py /usr/local/lib/python3.6/site-packages/cstar/cstarcli.py_bak
81,82c81,82
<             hosts = f.read().splitlines()
<
---
>             hosts = f.readlines()
>

[devel][jablonovskyr.dba@lcoa-lbif-xca1 ~]$ grep -n "f.read().splitlines()" /usr/local/lib/python3.6/site-packages/cstar/cstarcli.py
81:            hosts = f.read().splitlines()
```
Test modification:
```
cat list_nodes.txt
aaaa-aaaa-xca2
baaa-aaaa-xca2

cstar run --command='nodetool status' --host-file=list_nodes.txt
Job id is 322bb609-8d14-498f-9d78-b0f33221b2fe
Running /usr/local/lib/python3.6/site-packages/cstar/resources/commands/run.sh
Starting setup
Strategy: topology
DC parallel: True
Cluster parallel: True
Loading cluster topology
Preheating DNS cache
Preheating done
Done loading cluster topology
Generating endpoint mapping
Done generating endpoint mapping
Setup done
 +  Done, up      * Executing, up      !  Failed, up      . Waiting, up
 -  Done, down    / Executing, down    X  Failed, down    : Waiting, down
Cluster: Cluster_DBA
DC: A
+
DC: B
+
2 done, 0 failed, 0 executing
Job 322bb609-8d14-498f-9d78-b0f33221b2fe finished successfully
```

**Comment by rjablonovsky** [comment]
The Fix was added to source code.
