### ISSUE TITLE
Cstarpar hosts_variables error

### ISSUE THREAD

**Issue by treuherz** [spotify/cstar#68]
I've been unable to get cstarpar to run any commands due to what looked like a mis-assigned variable in the job initialisation:

```
$ cstarpar --seed-host $CASS_HOST --strategy=all  "hostname"
Job id is 29e97c20-e68e-4110-9764-f7f91aca797c
Starting setup
Strategy: all
Cluster parallel: False
DC parallel: False
Loading cluster topology
Traceback (most recent call last):
  File "/Users/et/.local/bin/cstarpar", line 8, in <module>
    sys.exit(main())
  File "/Users/et/.local/pipx/venvs/cstar/lib/python3.9/site-packages/cstar/cstarparcli.py", line 78, in main
    job.setup(
  File "/Users/et/.local/pipx/venvs/cstar/lib/python3.9/site-packages/cstar/job.py", line 271, in setup
    current_topology = current_topology | self.get_cluster_topology(seeds)
  File "/Users/et/.local/pipx/venvs/cstar/lib/python3.9/site-packages/cstar/job.py", line 105, in get_cluster_topology
    conn = self._connection(host)
  File "/Users/et/.local/pipx/venvs/cstar/lib/python3.9/site-packages/cstar/job.py", line 456, in _connection
    self._connections[host] = cstar.remote.Remote(host, self.ssh_username, self.ssh_password, self.ssh_identity_file, self.ssh_lib, self.get_host_variables(host))
  File "/Users/et/.local/pipx/venvs/cstar/lib/python3.9/site-packages/cstar/job.py", line 471, in get_host_variables
    if hostname in self.hosts_variables.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

As far as I can tell this can be fixed by adding the same processing of `--hosts-variables` to cstarparcli.py as already exists in cstarcli.py:

```python
    if args.hosts_variables:
        with open(args.hosts_variables) as f:
            hosts_variables = json.loads(f.read())
```

I'm happy to submit a PR for this, but I wanted to check if I'm along the right lines, as I've never used the host-variables arg and don't know if this would produce the intended behaviour

**Comment by smarsching** [comment]
I am not a maintainer, but I think you are right. I was experiencing the same problem and applying your suggested fix indeed fixed it for me. I created PR #69, so that if someone else is experiencing the same issue, they can apply the patch more quickly.

**Comment by adejanovski** [comment]
Thanks @treuherz and @smarsching for spotting and fixing this issue 🙏 
PR merged.
